#!/usr/bin/env bash

[ -n "${PROJECT_SETTINGS_SH}" ] && return || readonly PROJECT_SETTINGS_SH="SOURCED"
export TEST="N"

PREFIX="${USER}"
if [ "${PREFIX}zzz" == "zzz" ] ; then
	echo "PREFIX is not set.   Exiting"
	exit 1
fi

export PREFIX
export USER_UID="$( id -u )"
export USER_GID="$( id -g )"
export USER_NAME="$( id -un )"

export GW_GRPC_DIR="./GRPC"
export GW_PROGRAMS_DIR="./Web_Programs"

export FILE_MESSAGE="""
# This file has been generated by a script. Do not edit the values here.
# If you need to change the values, then change them in their settings file.
# $( date )
"""

if [ -f ./LocalSettings.sh ]; then
	source ./LocalSettings.sh
fi
